apiVersion: v1
kind: Pod
metadata:
  name: ai
spec:
  containers:
    - name: ai
      image: skynet:1997-08-29
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["big-gpu", "expensive-gpu"]
  tolerations:
    - key: "hardware"
      value: "gpu"
