apiVersion: v1
kind: Service
metadata:
  name: envbin
spec:
  selector:
    app: envbin
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: envbin
spec:
  rules:
    - host: envbin.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: envbin
              servicePort: 80
