apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: web
      image: nginx:1.18.0
      resources:
        requests:
          memory: 64Mi
          cpu: 100m
        limits:
          memory: 1Gi
          cpu: 1
