apiVersion: apps/v1
kind: Deployment
metadata:
  name: envbin
spec:
  selector:
    matchLabels:
      app: envbin
  template:
    metadata:
      labels:
        app: envbin
    spec:
      containers:
        - name: envbin
          image: mtinside/envbin:latest
---
apiVersion: v1
kind: Service
metadata:
  name: envbin
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: envbin
