apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blue-green
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.tls.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /blue-green
            backend:
              serviceName: blue-green
              servicePort: 80
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: blue-green-prod-tls
  {{- end }}
