apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: envbin.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: envbin
              servicePort: 8080
