apiVersion: v1
kind: Pod
metadata:
  name: envbin
  labels:
    app: envbin
spec:
  containers:
    - name: envbin
      image: mtinside/envbin:latest
---
apiVersion: v1
kind: Service
metadata:
  name: envbin
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: envbin
